### ISSUE TITLE
Do you accept 'Rails' functions ?

### ISSUE THREAD

**Issue by nicolas-besnard** [forgecrafted/finishing_moves#1]
Such as `present?`

**Comment by BattleBrisket** [comment]
You mean that you want to port Rails-specific methods out of Rails, or do you have a new method that would be Rails-only?

**Comment by nicolas-besnard** [comment]
I want to port Rails methods outside of it.

**Comment by BattleBrisket** [comment]
No, sorry. We designed FM to play nicely alongside major projects like Rails and Rack; porting methods would mean dealing with conflicts.

**Comment by BattleBrisket** [comment]
Clarification: if you want to add some logic that only exists in Rails, we would consider that, however it cannot conflict with Rails. 

e.g. if you want to add the same logic as `present?`, perhaps there's a synonymous word we could use.

Were you thinking of any other methods?

**Comment by nicolas-besnard** [comment]
I like to use `blank?` too

**Comment by BattleBrisket** [comment]
Perhaps we can borrow a few Rails methods, and only activate them when in a non-Rails environment. We'll consider it, but a pull request is always welcome.

**Comment by cmtonkinson** [comment]
@nicolas-besnard it sounds like you want a bunch of those methods - why not simply use the [activesupport](https://github.com/rails/rails/tree/master/activesupport/lib/active_support) gem directly?

**Comment by SkyBirdSoar** [comment]
#5

**Comment by BattleBrisket** [comment]
After some internal discussion, we've agreed that Finishing Moves must continue to be **Rails-agnostic**: it should work perfectly fine on it own, and play nice when loaded in a Rails environment.

If you want to use a specific piece of Ruby logic, then you should load the appropriate gem. Rails broke itself out into multiple gems for this very purpose.
