### ISSUE TITLE
Array :to_hash alias breaks :to_json for activesupport 4.1.6

### ISSUE THREAD

**Issue by patmalt** [forgecrafted/finishing_moves#10]
The :to_hash alias [1] breaks activesupport :to_json by wrapping the hash in double arrays.

For example:
```
{:name=>"patmalt", :email=>"patmalt@gmail.com"}.to_json
```
Should equal:
```
{"0": ["name", "patmalt"], "1": ["email", "patmalt@gmail.com"]}
```
but returns
```
{"0": [0, ["name", "patmalt"]], "1" :[1, ["email", "patmalt@gmail.com"]]}
```

[1] https://github.com/forgecrafted/finishing_moves/blob/a4119e835f8be913b66c1e52212da5dd19aaa11e/lib/finishing_moves/array.rb#L13

**Comment by BattleBrisket** [comment]
Yikes, Rails does make liberal use of the name `to_hash`, doesn't it? We'll remove our use of that method name.
