### ISSUE TITLE
Nil_chain custom return value with NoMethodError

### ISSUE THREAD

**Issue by D1ceWard** [forgecrafted/finishing_moves#13]
Hello,
As written in the wiki
> You can change the value that nil_chain returns when it catches a **NoMethodError or NameError** exception.

But it only set custom return with **NameError**

- `nil_chain('test') { raise NameError } => "test"`
- `nil_chain('test') { raise NoMethodError } => nil `

I'm using ruby 2.4.0

**Comment by BattleBrisket** [comment]
Good catch, @D1ceWard, and thanks for the PR! IIRC, this is a regression that opened up when I refactored the nil_chain method.
