### ISSUE TITLE
Do you think 'fetch!' could be a good idea ?

### ISSUE THREAD

**Issue by nicolas-besnard** [forgecrafted/finishing_moves#2]
I would like to know your opinion about a `fetch!` method. I would like to use it that way :

```Ruby
h = { 'a' => 100 }
h.fetch!('b', 200)          #=> 200
h                           #=> { "a" => 100, "b" => 200 }
```

I think it could replace `||=` that way :

```Ruby
def foo(options)
   options[:a] ||= "it's a a"
   options[:b] ||= true
end
```

```Ruby
def foo(options)
   options.fetch!('a', { |e| "it's a #{e}"}
   options.fetch!('b', true)
end
```

Just a though, I'm not sure that could be useful.

**Comment by BattleBrisket** [comment]
The goal of FM isn't to "replace" anything, but *augment*. Furthermore, we're looking to simplify situations that are onerous in default Ruby. `class_exists?` is the tightest example of this paradigm: there are ways to perform this check in Ruby, but it could be easier.

All that being said, I'm sure what to think of your suggestion. Did you use this in a real-world scenario, where it solved a real problem? If so, share that example! If not, well we don't want to be clever for its own sake. ;)

**Comment by SkyBirdSoar** [comment]
Well, I think it is a nice idea, especially the block which is cool.
But, the thing is, the block should only be called when the value for the key does not exist. So where does the method supply an argument to the block?
```ruby
options.fetch!('a', { |e| "it's a #{e}"} # Where does the e come from?
# Also you forgot to close the parenthesis. Gotcha!
# options.fetch!('a') { "it's a kelvin!" }
```
```ruby
(options[:score] ||= "A") ? "Great Job!" : "You need to buck up."
#  VS
options.fetch!(:score, "A") ? "Great Job!" : "You need to buck up."
```
Well... I would still choose `||=` over `fetch!` as it _expresses_ what its doing more clearly (although I'm sure new programmers won't understand it)

However, I would use `fetch!` if I need to use blocks. (`||=` with blocks just won't do)

**Comment by cmtonkinson** [comment]
@SkyBirdSoar when would it be beneficial to use a block, and how would that be different from what `||=` already allows?

**Comment by SkyBirdSoar** [comment]
I have no idea :P
But the thought of `||= do` and `||= {` doesn't appeal to me

**Comment by cmtonkinson** [comment]
I can definitely appreciate the appeal of which you speak, but unless someone can produce a real use case, we'll close this for now.
