### ISSUE TITLE
Check if method exists

### ISSUE THREAD

**Issue by BattleBrisket** [forgecrafted/finishing_moves#5]
Explore the *possibility* of utilizing `method_missing` in order to skip definition of methods that are defined by other gems.

**Comment by SkyBirdSoar** [comment]
I think this would break #3 and #4 if you do it the way I have in mind.
```ruby
module Finishing_Moves
  OBJECT_METHODS = {
    not_nil?: lambda do
       # some code here
    end
  }
end

class Object
  def method_missing meth, *args, &block
      if Finishing_Moves::OBJECT_METHODS.include? meth
        self.class_eval do
          define_method meth, &Finishing_Moves::OBJECT_METHODS[meth]
       end
    end
  end
end
```
Not sure if it works, but that's my idea currently

**Comment by SkyBirdSoar** [comment]
This could be a problem for developers as they cannot be certain of the behaviours of the methods anymore.

**Comment by SkyBirdSoar** [comment]
Actually, we shouldn't use `method_missing` as it might override `method_missing` created by other libraries. Instead, we should try `respond_to?`

**Comment by BattleBrisket** [comment]
As I emphasized in the original post, it's just a possibility to explore, and could very likely not work out. I like to avoid meta programming whenever possible for obvious reasons.

The testing and feedback is much appreciated, though, feel free to keep exploring!  :+1:

**Comment by SkyBirdSoar** [comment]
We could also try
```ruby
class S < FinishingMoves::Object
end
```

**Comment by SkyBirdSoar** [comment]
Or we might try
```ruby
module FinishingMoves
  class Factory
    def inject_object_methods obj
      def obj.same_as? other
        # ...
      end
    end
  end
end
```

**Comment by SkyBirdSoar** [comment]
[Refinements](http://6ftdan.com/allyourdev/2015/01/20/refinements-over-monkey-patching/#I4U3)

**Comment by BattleBrisket** [comment]
Per the resolution in #1, we're going to close this for now. We may revisit this in the future.
